create database cars_db;
use cars_db;


create table car_details (
	sale_id int,
	make char(20),
	type char(20),
	style char(20),
	cost_$ int,
	purchased_date date,
	salesman_id int);
    
insert into car_details(sale_id, make, type, style, cost_$, purchased_date, salesman_id)
values (1, 'Honda', 'Civic', 'Sedan', 40000, '2021-01-01', 1),
	   (2, 'Ford', 'Explorer', 'SUV', 35000, '2022-05-02', 2),
	   (3, 'Ford', 'Explorer', 'SUV', 25000, '2022-04-01', 3),
	   (4, 'Audi', 'A4', 'Sedan', 36000, '2021-05-01', 3),
	   (5, 'Honda', 'Civic', 'Sedan', 30000, '2022-08-12', 4),
	   (6, 'Nissan', 'Altima', 'Sedan', 48000, '2021-10-06', 2),
	   (7, 'Toyota', 'Corolla', 'Hatchback', 40000, '2021-12-31', 1),
	   (8, 'Toyota', 'Corolla', 'Hatchback', 60000, '2022-08-25', 1);

create table salespersons (
	salesman_id int,
	name char(20),
	age int,
	city char(20));

insert into salespersons (salesman_id, name, age, city)
values (1, 'John Smit', 28, 'New York'),
	   (2, 'Emily Wong', 35, 'San Franciso'),
	   (3, 'Tom Lee', 42, 'Seattle'),
	   (4, 'Lucy Chen', 31, 'LA');


select * from car_details;


-- Q. What is the total revenue generated by the sales of “Sedan” cars in each year?

select year(purchased_date) as year, sum(cost_$) as total_revenue
from car_details
where style = 'Sedan'
group by year;


/* 2. Write a SQL query to find the top 3 salespeople (salesman_id, name) based on the total sales amount they achieved.
The result should be sorted in descending order of the total sales amount. */

select s.salesman_id, s.name, sum(cd.cost_$) as total_sales
from salespersons s inner join car_details cd using(salesman_id)
group by 1,2
order by total_sales desc
limit 3;


/* 3. Write a SQL query to find the rank to each salesperson on the basis of number of car sold. 
Please use continuous rank and rank should be visible in your out-put. */

use cars_db;

select s.salesman_id, s.name, count(s.salesman_id) as cars_sold,
dense_rank() over (order by count(s.salesman_id) desc) as 'rank'
from salespersons s inner join car_details cd using(salesman_id)
group by 1,2;